[build]
builder = "nixpacks"
providers = ["nodejs"]
buildCommand = "npm install --no-package-lock"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/health"
healthcheckTimeout = 600
healthcheckInterval = 15

[deploy.env]
NODE_ENV = "production"
