[build]
builder = "nixpacks"
providers = ["nodejs"]
buildCommand = "npm install --no-package-lock"

[deploy]
startCommand = "node server.js"
# Temporarily disable health checks to allow deployment
# healthcheckPath = "/health"
# healthcheckTimeout = 300
# healthcheckInterval = 15

[deploy.env]
NODE_ENV = "production"
