[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm install --no-audit --no-fund --no-optional --legacy-peer-deps"]

[phases.build]
cmds = ["echo 'Skipping build phase'"]

[start]
cmd = "node server.js"
